practice01/p4_1/articles/urls.py
from django.urls import path
from . import views

app_name="articles"
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name="new"),
    path('create', views.create, name="create"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/prev', views.prev, name='prev'),
    path('<int:pk>/next', views.next, name='next'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

practice01/p4_1/pj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

practice01/p4_1/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

practice01/p4_1/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()
    return render(request, 'articles/create.html')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
    'article': article,
    }
    return render(request, 'articles/detail.html', context)

def prev(request, pk):
    article = Article.objects.get(pk=pk-1)
    print(article)
    print('aaaaaaaaaaaaa')
    context = {
    'article': article,
    }
    return render(request, 'articles/detail.html', context)

def next(request, pk):
    article = Article.objects.get(pk=pk+1)
    context = {
    'article': article,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
    'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

practice01/p4_1/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: end; margin-right: 10%">성공적으로 글이 작성되었습니다.</h1>
<a href="{% url 'articles:index' %}">index</a>
<hr>
{% endblock content %}

practice01/p4_1/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Detail Page</h1>
    <h3>{{ article.pk }}번째 글</h3>
    <hr>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <p>생성 날짜 : {{ article.created_at }}</p>
    <p>수정 날짜 : {{ article.updated_at }}</p>
    <hr>
    <a href="{% url 'articles:edit' article.pk %}">[UPDATE]</a>
    <a href="{% url 'articles:delete' article.pk %}">[DELETE]</a>
    <br>
    <a href="{% url 'articles:prev' article.pk %}">[prev]</a>
    <a href="{% url 'articles:next' article.pk %}">[next]</a>
    <br>
    <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

practice01/p4_1/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>edit</h1>
  <hr>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {# DB에서 필수적으로 필요한 내용 : title, content #}
    <label for="title">Title: </label>
    <input type="text" name="title" id="title" value="{{ article.title }}">
    <br>
    <label for="content">Content: </label>
    <textarea name="content">{{ article.content }}</textarea>
    <br>
    <input type="submit" value="제출">
  </form>
  <hr>
  <a href="{% url 'articles:main' %}">[BACK]</a>
{% endblock content %}

practice01/p4_1/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: end; margin-right: 10%">자유게시판</h1>
<a href="{% url 'articles:new' %}">잡담하기</a>
<hr>
{% for article in articles %}
    <p>글 번호 : {{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <p>글 내용 : {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
    <a href="{% url 'articles:edit' article.pk %}">[UPDATE]</a>
    <a href="{% url 'articles:delete' article.pk %}">[DELETE]</a>
    <hr>
{% endfor %}
{% endblock content %}

practice01/p4_1/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: end; margin-right: 10%">새 글 작 성</h1>
<form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {# DB에서 필수적으로 필요한 내용 : title, content #}
    <label for="title">작성자: </label>
    <input type="text" name="title" id="title">
    <br>
    <label for="content">내용: </label>
    <textarea name="content"></textarea>
    <br>
    <input type="submit" value="제출">
</form>
<hr>
<a href="{% url 'articles:index' %}">[뒤로가기]</a>
{% endblock content %}