day04/articles/urls.py
from django.urls import path
from . import views

app_name="articles"
urlpatterns = [
    path('', views.index, name="index"),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),

    # ------------------------------------------

    path('main/', views.main, name='main'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

day04/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

day04/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} {self.content}'
    

day04/articles/views.py
from email import message
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.
def index(request):
  name = 'moon3'
  fruits = ['귤', '딸기', '사과', '바나나', '파인애플']
  hate = ['구아바', '사과' ]

  context = {
    'name': name,
    'fruits': fruits,
    'hate': hate,
  }
  return render(request, 'articles/index.html', context)

def throw(request):
  return render(request, 'articles/throw.html')

def catch(request):
  message = request.GET.get('message')
  print(message)
  context = {
    'message': message,
  }
  
  return render(request, 'articles/catch.html', context)

def main(request):
  articles = Article.objects.all()

  context = {
    'articles': articles,
  }
  #print(context)

  return render(request, 'articles/main.html', context)

def new(request):
  return render(request, 'articles/new.html')

def create(request):
  title = request.POST.get('title')
  content = request.POST.get('content')

  article = Article(title=title, content=content)
  article.save()

  return redirect('articles:main')

def detail(request, pk):
  article = Article.objects.get(pk=pk)
  context = {
    'article': article,
  }
  return render(request, 'articles/detail.html', context)

def delete(request, pk):
  article = Article.objects.get(pk=pk)
  article.delete()
  return redirect('articles:main')

def edit(request, pk):
  article = Article.objects.get(pk=pk)
  context = {
    'article': article,
  }
  return render(request, 'articles/edit.html', context)

def update(request, pk):
  article = Article.objects.get(pk=pk)
  article.title = request.POST.get('title')
  article.content = request.POST.get('content')
  article.save()
  return redirect('articles:detail', article.pk)

day04/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>catch</h1>
  <p>받은 데이터 : {{ message }}</p>
  <a href="{% url 'articles:index' %}">처음으로</a>
  <a href="{% url 'articles:throw' %}">다시 던지러 ㄱㄱ</a>
{% endblock content %}

day04/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Detail Page</h1>
  <h3>{{ article.pk }}번째 글</h3>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>생성 날짜 : {{ article.created_at }}</p>
  <p>수정 날짜 : {{ article.updated_at }}</p>
  <hr>
  <a href="{% url 'articles:main' %}">[BACK]</a>
{% endblock content %}

day04/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <button type="button" class="btn btn-primary">{{ name }}</button>
  <a href="{% url 'articles:throw' %}">던지기</a>
  <a href="{% url 'articles:catch' %}">받기</a>
  <a href="{% url 'articles:main' %}">메인</a>
  <a href="{% url 'articles:new' %}">등록</a>
  <hr>
  <p>전체출력</p>
  <p>fruit list: {{ fruits}} </p>
  <p> hate list: {{ hate}} </p>
  <hr>
  <p> just show</p>
  {% for fruit in fruits %}
  <p> {{fruit}}</p>
  {% endfor %}
  <hr>
  <p> 싫어하는 과일 출력 안하기</p>
  {% for fruit in fruits %}
    {% if fruit not in hate %}
      <p>{{fruit}}</p>
    {% endif %}
  {% endfor %}
  <hr>
  <p>2글자 이상인 과일만 출력하기</p>
  {% for fruit in fruits %}
    {% if fruit not in hate %}
      {% if fruit|length > 1 %}
        <p>{{fruit}}</p>
      {% endif %}
    {% endif %}
  {% endfor %}
  <hr>
  <p>3글자 이하인 과일만 출력하기</p>
  {% for fruit in fruits %}
    {% if fruit not in hate %}
      {% if fruit|length > 1 %}
        <p>{{fruit|truncatechars:3}}</p>
      {% endif %}
    {% endif %}
  {% endfor %}

{% endblock content %}

day04/articles/templates/articles/main.html
{% extends 'base.html' %}

{% block content %}
  <h1>main</h1>
  <a href="{% url 'articles:index' %}">처음으로</a>
  <a href="{% url 'articles:new' %}">등록</a>
  <hr>
  {% for article in articles %}
    <div>글 번호 : {{ article.pk }}</div>
    <div>글 제목 : {{ article.title }}</div>
    <div>글 내용 : {{ article.content }}</div>
    <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
    <a href="{% url 'articles:edit' article.pk %}">[UPDATE]</a>
    <a href="{% url 'articles:delete' article.pk %}">[DELETE]</a>
    <hr>
  {% endfor %}
{% endblock content %}

day04/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>new</h1>
  <a href="{% url 'articles:index' %}">처음으로</a>
  <hr>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {# DB에서 필수적으로 필요한 내용 : title, content #}
    <label for="title">Title: </label>
    <input type="text" name="title" id="title">
    <br>
    <label for="content">Content: </label>
    <textarea name="content"></textarea>
    <br>
    <input type="submit" value="제출">
  </form>
  <hr>
{% endblock content %}

day04/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw</label>
    <input type="text" name="message" id="message">
    <input type="submit" value="제출">
  </form>
  <a href="{% url 'articles:index' %}">처음으로</a>
{% endblock content %}