practice01/p04/pp04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('throws/', include('throws.urls')),
]

practice01/p04/throws/urls.py
from django.urls import path
from . import views
app_name="throws"
urlpatterns = [
    path('first/', views.first, name='first'),
    path('second/', views.second, name='second'),
    path('third/', views.third, name='third'),
]

practice01/p04/throws/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    t_mes = request.GET.get('t_mes')
    if t_mes == None:
        t_mes = 'nothing'
    context = {
        't_mes': t_mes,
    }

    return render(request, 'throws/first.html', context)

def second(request):
    f_mes = request.GET.get('f_mes')
    
    context = {
        'f_mes': f_mes,
    }
    return render(request, 'throws/second.html', context)

def third(request):
    s_mes = request.GET.get('s_mes')

    context = {
        's_mes': s_mes,
    }
    return render(request, 'throws/third.html', context)

practice01/p04/throws/templates/throws/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>catch! I catch {{ t_mes }}</h3>
    <form action="{% url 'throws:second' %}" method="GET">
        <label for="f_mes">throw!</label>
        <input type="text" name="f_mes" id="f_mes">
        <input type="submit" value="슉">
    </form>
</body>
</html>

practice01/p04/throws/templates/throws/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>catch! I catch {{ f_mes }}</h3>
    <form action="{% url 'throws:third' %}" method="GET">
        <label for="s_mes2">throw!</label>
        <input type="text" name="s_mes2" id="s_mes2">
        <label for="s_mes">twice!</label>
        <input type="text" name="s_mes" id="s_mes">
        <input type="submit" value="슉슉">
    </form>
</body>
</html>

practice01/p04/throws/templates/throws/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>catch! I catch only {{ s_mes }} ㅜㅜ</h3>
    <form action="{% url 'throws:first' %}" method="GET">
        <label for="t_mes">throw!</label>
        <input type="text" name="t_mes" id="t_mes">
        <input type="submit" value="슉슉슉">
    </form>
</body>
</html>