practice02/p03/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

practice02/p03/movies/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=50)
    director = models.CharField(max_length=30)
    comment = models.TextField()

practice02/p03/movies/forms.py
from django import forms
from .models import Movies

class MovoiesForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': '세 얼간이'
            }
        ),
    )
    director = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': '라지쿠마르 히라니'
            }
        ),
    )
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': '나 얼간이 아니다!',
                'cols': 40,
                'rows': 3,
            }
        ),
    )
    class Meta:
        model = Movies
        fields = '__all__'

practice02/p03/movies/views.py
from django.shortcuts import render, redirect
from .models import Movies
from .forms import MovoiesForm
from django.views.decorators.http import require_http_methods, require_POST, require_safe

# Create your views here.
@require_safe
def index(request):
    movies = Movies.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovoiesForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovoiesForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

@require_safe
def detail(request, pk):
    movie = Movies.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)

@require_POST
def delete(request, pk):
    if request.method == 'POST':
        movie = Movies.objects.get(pk=pk)
        movie.delete()
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = Movies.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovoiesForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovoiesForm(instance=movie)
    
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

practice02/p03/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>CREATE</h1>    
    <form action="{% url 'movies:create' %}" method='Post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

practice02/p03/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>DETAIL</h1>
    <h2>{{ movie.pk }}번째 글</h2>
    <hr>
    <p>제목 : {{ movie.title }}</p>
    <p>감독 : {{ movie.director }}</p>
    <p>코멘트 : {{ movie.comment }}</p>
    <hr>
    <a href="{% url 'movies:update' movie.pk %}">UPDATE</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    
    <a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

practice02/p03/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Movies</h1>
    <a href="{% url 'movies:create' %}">CREATE</a>
    <hr>
    {% for movie in movies %}
        <p>제목 : {{ movie.title }}</p>
        <p>감독 : {{ movie.director }}</p>
        <a href="{% url 'movies:detail' movie.pk %}">DETAIL</a>
        <hr>
    {% endfor %}
{% endblock content %}

practice02/p03/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>update</h1>
    <form action="{% url 'movies:update' movie.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
    
{% endblock content %}